spring.application.name=ConfigServer
server.port=8888

# Activate native file system mode
spring.profiles.active=native,dev
spring.cloud.config.server.native.search-locations=file:///C:/config-repo

# Enable monitoring (optional)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always